### ISSUE TITLE
Polymer CSS Build can result in missing styles.

### ISSUE THREAD

**Issue by nik3daz** [PolymerLabs/polymer-css-build#6]
When inlining styles, PCB leaves leftover style includes in index.js:155 (presumably so that they can get resolved at runtime if possible). However, Polymer sees the css-build="true" on the dom module and then in src/standard/styling.html:66, returns before collectStyles which searches for extra style modules.

Basically, since the style includes don't actually get resolved properly, I think at this point, Polymer CSS Build should just throw an error (or at least a warning) if there are unresolved style modules so that developers know that they may have made a typo or forgotten to add all files to the Polymer CSS Build step.

**Comment by danbeam** [comment]
it wasn't mentioned, but this broke Chrome's history UI

https://bugs.chromium.org/p/chromium/issues/detail?id=691436

**Comment by azakus** [comment]
Should be fixed by #8
